AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Max: 50
  Exclude:
    - 'spec/**/*.rb'